// Amigo · Kaibigan: Tagalog past the basics, for Blake (rusty mission Tagalog,
// the Philippines 2002–2004). He asked for everyday conversation, listening at
// native speed, and the grammar that's slipped. Each unit is a real
// conversation between two people, recorded in two Filipino voices at native
// speed, and the grammar it uses, in three lessons: Listen, Grammar, Say it.
// The rules are in amigo/README.md; tools/test-amigo.mjs checks every one.
(function (root) {
  'use strict';

  const COURSE = {
    id: 'tl2',
    lang: 'tl',
    kind: 'conversation',
    name: 'Tagalog',
    title: 'Past the basics',
    who: 'For Tatay · past the basics',
    voices: ['fil-PH', 'fil', 'tl-PH', 'tl'],
    // The recordings' voices (tools/amigo-voice.mjs): A is a man, B a woman,
    // at native speed (the first course's are slowed to 0.9).
    speakers: { A: 'fil-ph-Neural2-D', B: 'fil-ph-Neural2-A' },
    rate: 1,
    lessonNames: ['Listen', 'Grammar', 'Say it'],
    praise: ['Tama!', 'Magaling!', 'Ang galing!'],
    units: [
      {
        id: 'kumustahan-ulit', title: 'Kumustahan ulit', sub: 'Catching up',
        blurb: 'Running into an old friend, and what you’ve both done since: finished actions.',
        done: 'Ang galing mo!', doneNote: '“Ang galing mo!” means “You’re great at this!”',
        dialog: {
          setting: 'Ramon runs into Liza, an old friend, at the mall.',
          people: { A: 'Ramon', B: 'Liza' },
          lines: [
            { who: 'A', t: 'Uy, Liza! Ikaw ba ’yan? Ang tagal nating hindi nagkita!', en: 'Hey, Liza! Is that you? We haven’t seen each other in so long!' },
            { who: 'B', t: 'Ramon! Oo nga, mga limang taon na siguro. Kumusta ka na?', en: 'Ramon! That’s right, maybe five years now. How have you been?' },
            { who: 'A', t: 'Mabuti naman. Lumipat kami sa Laguna noong isang taon. Ikaw, saan ka na nakatira ngayon?', en: 'Good. We moved to Laguna last year. And you, where do you live now?' },
            { who: 'B', t: 'Nandito pa rin ako sa Quezon City, pero nagtrabaho ako sa Dubai nang tatlong taon.', en: 'I’m still here in Quezon City, but I worked in Dubai for three years.' },
            { who: 'A', t: 'Talaga? Kailan ka umuwi?', en: 'Really? When did you come home?' },
            { who: 'B', t: 'Umuwi ako noong Disyembre. Na-miss ko kasi ang pamilya ko.', en: 'I came home in December. I missed my family, you see.',
              note: '“Na-miss” is Taglish: the English “miss” with na-, the finished form.' },
            { who: 'A', t: 'Naiintindihan ko. Nag-asawa ka na ba?', en: 'I understand. Have you gotten married?' },
            { who: 'B', t: 'Oo! Ikinasal kami noong Pebrero. Ikaw, may mga anak ka na?', en: 'Yes! We got married in February. And you, do you have kids now?' },
            { who: 'A', t: 'Dalawa na. Ipinanganak ang bunso namin noong Agosto.', en: 'Two now. Our youngest was born in August.' },
            { who: 'B', t: 'Wow, congrats! Ano ang pangalan niya?', en: 'Wow, congrats! What’s the baby’s name?' },
            { who: 'A', t: 'Miguel. Uy, kumain ka na ba? Tara, kain tayo!', en: 'Miguel. Hey, have you eaten? Come on, let’s eat!' },
            { who: 'B', t: 'Sige, pero libre ko ngayon!', en: 'Sure, but it’s on me this time!',
              note: '“Libre ko” is “my treat”: libre is free, so “it’s free, on me.”' },
          ],
        },
        questions: [
          { q: 'How long since they last saw each other?', right: 'About five years', wrong: ['About a year', 'About ten years'], line: 2 },
          { q: 'Where did Ramon’s family move?', right: 'To Laguna', wrong: ['To Quezon City', 'To Dubai'], line: 3 },
          { q: 'What did Liza do in Dubai?', right: 'She worked there for three years', wrong: ['She studied there for three years', 'She got married there'], line: 4 },
          { q: 'Why did Liza come home?', right: 'She missed her family', wrong: ['She lost her job', 'Her contract ended'], line: 6 },
          { q: 'When was Ramon’s youngest born?', right: 'In August', wrong: ['In December', 'In February'], line: 9 },
          { q: 'Who pays for the meal?', right: 'Liza', wrong: ['Ramon', 'They split it'], line: 12 },
        ],
        gaps: [
          { line: 3, word: 'Lumipat', wrong: ['Lumilipat', 'Lilipat'] },
          { line: 6, word: 'Umuwi', wrong: ['Umuuwi', 'Uuwi'] },
          { line: 8, word: 'Ikinasal', wrong: ['Ikinakasal', 'Ikakasal'] },
        ],
        grammar: {
          title: 'Finished actions',
          points: [
            'Tagalog verbs change with the action, not the clock: finished, still going, or not started yet.',
            'An -um- verb takes -um- after its first consonant, or in front when it starts with a vowel: kain → kumain (ate), lipat → lumipat (moved), uwi → umuwi (went home).',
            'A mag- verb turns into nag-: magtrabaho → nagtrabaho (worked), mag-asawa → nag-asawa (married).',
            'A verb about the thing done to takes -in- after its first consonant: basa → binasa (read it); before l it goes in front as ni-: luto → niluto (cooked it). An i- verb takes it too: ipanganak → ipinanganak (was born).',
          ],
          table: [['kain', 'kumain', 'ate'], ['uwi', 'umuwi', 'went home'], ['magtrabaho', 'nagtrabaho', 'worked'], ['basa', 'binasa', 'read (it)'], ['luto', 'niluto', 'cooked (it)']],
        },
        forms: [
          { prompt: 'Kahapon, ___ ako ng adobo.', root: 'luto', right: 'nagluto', wrong: ['nagluluto', 'magluluto'], en: 'Yesterday I cooked adobo.' },
          { prompt: '___ si Tatay sa opisina kaninang umaga.', root: 'punta', right: 'Pumunta', wrong: ['Pumupunta', 'Pupunta'], en: 'Dad went to the office this morning.' },
          { prompt: '___ kami sa labas kagabi.', root: 'kain', right: 'Kumain', wrong: ['Kumakain', 'Kakain'], en: 'We ate out last night.' },
          { prompt: '___ namin ang pelikula noong Sabado.', root: 'panood', right: 'Pinanood', wrong: ['Pinapanood', 'Papanoorin'], en: 'We watched the movie on Saturday.' },
          { prompt: '___ kami ng bahay noong isang taon.', root: 'bili', right: 'Bumili', wrong: ['Bumibili', 'Bibili'], en: 'We bought a house last year.' },
          { prompt: '___ ko ang sulat mo kanina.', root: 'basa', right: 'Binasa', wrong: ['Binabasa', 'Babasahin'], en: 'I read your letter earlier.' },
        ],
        builds: [
          { t: 'Kumain ka na ba?', en: 'Have you eaten yet?' },
          { t: 'Lumipat kami sa Laguna noong isang taon.', en: 'We moved to Laguna last year.' },
          { t: 'Umuwi ako noong Disyembre.', en: 'I came home in December.' },
          { t: 'Nagtrabaho siya sa Dubai nang tatlong taon.', en: 'She worked in Dubai for three years.' },
        ],
        says: [
          { t: 'Ang tagal nating hindi nagkita!', en: 'We haven’t seen each other in so long!' },
          { t: 'Saan ka na nakatira ngayon?', en: 'Where do you live now?' },
          { t: 'Kailan ka umuwi?', en: 'When did you come home?' },
          { t: 'Nag-asawa ka na ba?', en: 'Have you gotten married?' },
          { t: 'Libre ko ngayon!', en: 'It’s on me this time!' },
        ],
        scenes: [
          { kind: 'What do you say?', prompt: 'You run into a friend you haven’t seen in years.', right: 'Ang tagal nating hindi nagkita!', wrong: ['Ingat ka!', 'Busog na ako.'] },
          { kind: 'What do you ask?', prompt: 'Your friend worked abroad. You want to know when she got back.', right: 'Kailan ka umuwi?', wrong: ['Saan ka pupunta?', 'Kailan ka aalis?'],
            note: '“Kailan ka aalis?” is “When will you leave?”, not yet started.' },
          { kind: 'What do you say?', prompt: 'You want to pay for your friend’s lunch.', right: 'Libre ko!', wrong: ['Bayad po!', 'Sige, ikaw na.'],
            note: '“Bayad po!” is what you say handing the fare on a jeep.' },
        ],
      },
      {
        id: 'sa-palengke', title: 'Sa palengke', sub: 'At the market',
        blurb: 'Buying vegetables and fruit at the wet market, and haggling like a regular: who the sentence is about.',
        done: 'Sulit!', doneNote: '“Sulit!” means “Worth every peso!”',
        dialog: {
          setting: 'Paolo buys vegetables and fruit from Cora, his regular vendor at the wet market.',
          people: { A: 'Paolo', B: 'Cora' },
          lines: [
            { who: 'A', t: 'Magandang umaga po, Aling Cora! Magkano po ang kangkong ngayon?', en: 'Good morning, Aling Cora! How much is the kangkong today?',
              note: '“Aling” goes before an older woman’s first name, and “Mang” before an older man’s.' },
            { who: 'B', t: 'Uy, suki! Bente ang isang tali. Ano’ng lulutuin mo?', en: 'Hey, suki! Twenty a bundle. What are you cooking?',
              note: '“Suki” is a regular customer, and also the vendor you always buy from.' },
            { who: 'A', t: 'Sinigang na bangus po. Bumili na po ako ng isda kay Mang Ben.', en: 'Milkfish sinigang. I already bought fish from Mang Ben.' },
            { who: 'B', t: 'E di bilhin mo na rin ’tong sitaw. Bente singko lang ang tali.', en: 'Then buy these string beans too. Only twenty-five a bundle.' },
            { who: 'A', t: 'Sige po, tatlong kangkong at isang sitaw. Wala na po bang tawad? Suki n’yo naman ako.', en: 'Okay, three bundles of kangkong and one of string beans. Any discount? I’m your regular, after all.' },
            { who: 'B', t: 'Sige na nga, otsenta na lang. Suki kita, e.', en: 'Oh, all right, eighty then. You’re my regular, after all.' },
            { who: 'A', t: 'Salamat po! May mangga rin po ba kayo? Magkano po ang kilo?', en: 'Thank you! Do you have mangoes too? How much a kilo?' },
            { who: 'B', t: 'Meron. Galing Guimaras ’yan, ang tamis! Siyento bente ang kilo.', en: 'I do. They’re from Guimaras, so sweet! A hundred and twenty a kilo.',
              note: '“Siyento bente” is a hundred and twenty: prices are often said in numbers from Spanish.' },
            { who: 'A', t: 'Isang kilo po. Kayo na po ang pumili ng matatamis.', en: 'One kilo, please. You pick the sweet ones.' },
            { who: 'B', t: 'Heto, pinili ko ang pinakamatatamis. Ilagay ko na sa eco bag mo?', en: 'Here, I picked the sweetest ones. Shall I put them in your eco bag?',
              note: '“Eco bag” is Taglish for a reusable shopping bag.' },
            { who: 'A', t: 'Opo, salamat po. Magkano po lahat? Wala po akong barya, isang libo lang.', en: 'Yes, thanks. How much for everything? I have nothing smaller than a thousand.' },
            { who: 'B', t: 'Dos siyentos lahat. Naku, wala na akong panukli. Bayaran mo na lang ako bukas.', en: 'Two hundred in all. Oh dear, I’m out of change. Just pay me tomorrow.' },
          ],
        },
        questions: [
          { q: 'How much is a bundle of kangkong?', right: 'Twenty pesos', wrong: ['Twenty-five pesos', 'Eighty pesos'], line: 2 },
          { q: 'Where did Paolo get the fish?', right: 'From Mang Ben', wrong: ['From Aling Cora', 'He hasn’t bought it yet'], line: 3 },
          { q: 'What else does Cora get him to buy?', right: 'String beans', wrong: ['Mangoes', 'More kangkong'], line: 4 },
          { q: 'Why does Cora agree to a lower price?', right: 'He’s her regular customer', wrong: ['He’s buying a lot', 'He’s buying mangoes too'], line: 6 },
          { q: 'How much is a kilo of mangoes?', right: 'A hundred and twenty pesos', wrong: ['Eighty pesos', 'Two hundred pesos'], line: 8 },
          { q: 'What does Cora tell Paolo to do?', right: 'Pay her tomorrow', wrong: ['Get change from Mang Ben', 'Pay her next week'], line: 12 },
        ],
        gaps: [
          { line: 3, word: 'Bumili', wrong: ['Binili', 'Bilhin'] },
          { line: 4, word: 'bilhin', wrong: ['bumili', 'bibili'] },
          { line: 12, word: 'Bayaran', wrong: ['Magbayad', 'Binayaran'] },
        ],
        grammar: {
          title: 'Who it’s about',
          points: [
            'The verb’s form shows who or what the sentence is about: that one takes ang (si before a name, or ako, ikaw, siya). The doer or thing it isn’t about takes ng (ni before a name, or ko, mo, niya); the person or place it’s from or to takes sa (kay before a name).',
            'An -um- or mag- verb is about the doer: bili → bumili, bayad → magbayad. Bumili ako ng isda (I bought some fish).',
            'An -in verb is about the thing, usually a particular one: bili → binili (bought it), bilhin (buy it). Binili ko ang isda (I bought the fish).',
            'An i- verb is about a thing handed over or put somewhere: bigay → ibigay (give it), lagay → ilagay (put it). An -an verb is about who or what gets it: bigay → bigyan (give someone), bayad → bayaran (pay someone), dagdag → dagdagan (add to it).',
          ],
          table: [['bili', 'bumili', 'buy'], ['bili', 'bilhin', 'buy (it)'], ['bigay', 'ibigay', 'give (it)'], ['balot', 'ibalot', 'wrap (it)'], ['bayad', 'bayaran', 'pay (someone)']],
        },
        forms: [
          { prompt: '___ ako ng isang kilong bangus.', root: 'bili', right: 'Bumili', wrong: ['Binili', 'Bilhin'], en: 'I bought a kilo of milkfish.' },
          { prompt: '___ ko ang mangga kay Aling Cora kahapon.', root: 'bili', right: 'Binili', wrong: ['Bumili', 'Bilhin'], en: 'I bought the mangoes from Aling Cora yesterday.' },
          { prompt: '___ n’yo na rin po ang isda.', root: 'linis', right: 'Linisin', wrong: ['Maglinis', 'Naglinis'], en: 'Please clean the fish too.' },
          { prompt: '___ ko na ang bayad sa tindera.', root: 'bigay', right: 'Ibinigay', wrong: ['Nagbigay', 'Binigyan'], en: 'I already handed the payment to the vendor.' },
          { prompt: '___ ako ni Aling Cora ng isang mangga.', root: 'bigay', right: 'Binigyan', wrong: ['Ibinigay', 'Nagbigay'], en: 'Aling Cora gave me a mango.' },
          { prompt: '___ n’yo naman po ng isa.', root: 'dagdag', right: 'Dagdagan', wrong: ['Magdagdag', 'Idagdag'], en: 'Throw in one more, please.' },
        ],
        builds: [
          { t: 'Bumili ka na ba ng isda?', en: 'Have you bought fish yet?' },
          { t: 'Ano ang binili mo sa palengke?', en: 'What did you buy at the market?' },
          { t: 'Ilagay n’yo na lang po rito.', en: 'Just put it in here, please.' },
          { t: 'Binayaran ko na si Aling Cora.', en: 'I’ve already paid Aling Cora.' },
        ],
        says: [
          { t: 'Magkano po ang isang kilo?', en: 'How much is a kilo?' },
          { t: 'Wala na po bang tawad?', en: 'Can you go any lower?',
            note: '“Tawad” is the discount you haggle for.' },
          { t: 'Suki n’yo naman po ako.', en: 'I’m your regular, after all.',
            note: '“N’yo” is ninyo, the polite “your” that goes with po.' },
          { t: 'Kayo na po ang pumili.', en: 'You choose for me, please.' },
          { t: 'Magkano po lahat?', en: 'How much for everything?' },
        ],
        scenes: [
          { kind: 'What do you ask?', prompt: 'The price is a bit high. You ask the vendor if she can go lower.', right: 'Wala na po bang tawad?', wrong: ['Dagdagan n’yo naman po ng isa.', 'May mangga rin po ba kayo?'],
            note: '“Dagdagan n’yo naman po ng isa” asks her to throw in one more, not to lower the price.' },
          { kind: 'What do you say?', prompt: 'You’d rather the vendor choose the sweetest mangoes for you.', right: 'Kayo na po ang pumili.', wrong: ['Ako na po ang pipili.', 'Pinili ko na po.'],
            note: '“Ako na po ang pipili” is “I’ll pick them myself.”' },
          { kind: 'What do you ask?', prompt: 'A friend shows off a big, fresh fish. You want to know who sold it to him.', right: 'Kanino mo binili ’yan?', wrong: ['Kailan mo binili ’yan?', 'Magkano ’yan?'],
            note: '“Kailan mo binili ’yan?” asks when he bought it, not from whom.' },
        ],
      },
      {
        id: 'sa-jeep', title: 'Sa jeep', sub: 'On the jeep',
        blurb: 'Riding a jeepney and asking the way: places and directions with sa.',
        done: 'Nakarating ka na!', doneNote: '“Nakarating ka na!” means “You’ve made it!”',
        dialog: {
          setting: 'Jomar asks Tess, the woman next to him on a jeep, how to get to his grandma’s house.',
          people: { A: 'Jomar', B: 'Tess' },
          lines: [
            { who: 'A', t: 'Ate, dadaan po ba ’to sa Cubao?', en: 'Ate, does this jeep go through Cubao?' },
            { who: 'B', t: 'Oo, dadaan. Saan ka ba papunta?', en: 'Yes, it does. Where are you headed?' },
            { who: 'A', t: 'Papunta po ako kina Lola. Galing pa po ako sa Batangas.', en: 'I’m going to my grandma’s. I’ve come all the way from Batangas.',
              note: '“Kina Lola” is “to Lola’s place”: with a person’s name, sa becomes kay, or kina for the family.' },
            { who: 'B', t: 'Ay, first time mo rito? Nasaan ba ’yung bahay nila?', en: 'Oh, first time here? Where’s their house?' },
            { who: 'A', t: 'Nasa likod daw po ng simbahan, malapit sa palengke. Saan po ako bababa?', en: 'She says it’s behind the church, near the market. Where do I get off?' },
            { who: 'B', t: 'Ah, alam ko ’yan! Bumaba ka sa harap ng Jollibee.', en: 'Oh, I know where that is! Get off in front of the Jollibee.' },
            { who: 'A', t: 'Sa harap po ng Jollibee. Tapos, saan po ako liliko?', en: 'In front of the Jollibee. Then where do I turn?' },
            { who: 'B', t: 'Pagbaba mo, kumanan ka sa unang kanto. Diretso ka lang, nasa kaliwa mo na ’yung simbahan.', en: 'When you get off, turn right at the first corner. Keep going straight, and the church will be on your left.' },
            { who: 'A', t: 'Kanan, tapos diretso. Salamat po! Pakiabot naman po ng bayad ko.', en: 'Right, then straight on. Thank you! Could you pass my fare up, please?',
              note: 'On a jeep, riders pass the fare hand to hand up to the driver.' },
            { who: 'B', t: 'Sige. Manong, bayad po! Isa, Cubao.', en: 'Sure. Manong, fare! One, to Cubao.' },
            { who: 'A', t: 'Uy, ayan na ’yung Jollibee! Para po! Sa tabi lang po, Manong.', en: 'Oh, there’s the Jollibee! Stop, please! By the side is fine, Manong.',
              note: '“Para” comes from the Spanish parar, to stop.' },
            { who: 'B', t: 'Ingat ka, ha! Itago mo ’yang cellphone mo sa loob ng bag.', en: 'Take care, okay? Keep that phone of yours inside your bag.' },
          ],
        },
        questions: [
          { q: 'Where has Jomar come from?', right: 'From Batangas', wrong: ['From Cubao', 'From his grandma’s house'], line: 3 },
          { q: 'Where is his grandma’s house?', right: 'Behind the church', wrong: ['In front of the church', 'In front of the Jollibee'], line: 5 },
          { q: 'Where should he get off?', right: 'In front of the Jollibee', wrong: ['Behind the church', 'By the market'], line: 6 },
          { q: 'What should he do at the first corner?', right: 'Turn right', wrong: ['Turn left', 'Keep going straight'], line: 8 },
          { q: 'How does Jomar pay his fare?', right: 'Tess passes it up to the driver', wrong: ['He pays when he gets off', 'Tess pays it for him'], line: 9 },
          { q: 'What does Tess tell him at the end?', right: 'To keep his phone in his bag', wrong: ['To turn left at the corner', 'To get off by the market'], line: 12 },
        ],
        gaps: [
          { line: 2, word: 'Saan', wrong: ['Nasaan', 'Taga-saan'] },
          { line: 5, word: 'sa', wrong: ['ng', 'nasa'] },
          { line: 8, word: 'kaliwa', wrong: ['kumaliwa', 'pakaliwa'] },
        ],
        grammar: {
          title: 'Places and directions',
          points: [
            'Sa marks a place, and the words around it say to, at or from: pupunta sa Cubao → going to Cubao, bababa sa kanto → getting off at the corner. Papunta (on the way to) and galing (coming from) need no other verb: Galing ako sa Batangas → I’ve come from Batangas.',
            'Nasa is “is at” or “is in”, with no other verb: Nasa Cubao si Lola → Lola is in Cubao. To ask where something is, say Nasaan (in everyday talk, Saan too): Nasaan ang simbahan? → Where’s the church? For where someone goes or does something, only Saan: Saan ka bababa? → Where are you getting off?',
            'Tabi (side), harap (front), likod (back) and loob (inside) take ng before the place: sa harap ng Jollibee → in front of the Jollibee, nasa loob ng bag → in the bag. With ko or mo there’s no ng: sa tabi ko → next to me. Malapit (near) takes sa: malapit sa palengke → near the market.',
            'Kanan is right and kaliwa is left: kumanan → turn right, kumaliwa → turn left, nasa kaliwa mo → on your left. Diretso is straight on: Diretso lang → keep going straight.',
          ],
          table: [['tabi', 'sa tabi ng', 'beside'], ['harap', 'sa harap ng', 'in front of'], ['likod', 'sa likod ng', 'behind'], ['loob', 'sa loob ng', 'inside'], ['lapit', 'malapit sa', 'near']],
        },
        forms: [
          { prompt: '___ lang sa simbahan ang bahay nila.', root: 'lapit', right: 'Malapit', wrong: ['Lumapit', 'Lapitan'], en: 'Their house is close to the church.' },
          { prompt: 'May upuan pa sa ___ ko.', root: 'tabi', right: 'tabi', wrong: ['itabi', 'tumabi'], en: 'There’s still a seat next to me.' },
          { prompt: 'Hintayin mo ako sa ___ ng simbahan.', root: 'harap', right: 'harap', wrong: ['humarap', 'harapin'], en: 'Wait for me in front of the church.' },
          { prompt: 'Nasa ___ pa ng jeep ang payong ko!', root: 'loob', right: 'loob', wrong: ['paloob', 'nilooban'], en: 'My umbrella’s still inside the jeep!' },
          { prompt: '___ po ako puwedeng sumakay papuntang Quiapo?', root: 'saan', right: 'Saan', wrong: ['Nasaan', 'Taga-saan'], en: 'Where can I get a ride to Quiapo?' },
          { prompt: 'Tumawag si Nanay habang ___ ako sa trabaho.', root: 'punta', right: 'papunta', wrong: ['pumunta', 'pupunta'], en: 'Mom called while I was on my way to work.' },
        ],
        builds: [
          { t: 'Bumaba ka sa harap ng Jollibee.', en: 'Get off in front of the Jollibee.' },
          { t: 'Nasa likod ng simbahan ang bahay ni Lola.', en: 'Lola’s house is behind the church.' },
          { t: 'Galing po ako sa Batangas.', en: 'I’ve come from Batangas.' },
          { t: 'Kumanan ka sa kanto, tapos diretso lang.', en: 'Turn right at the corner, then go straight.' },
        ],
        says: [
          { t: 'Dadaan po ba ’to sa Cubao?', en: 'Does this jeep go through Cubao?' },
          { t: 'Nasaan po ang sakayan ng jeep?', en: 'Where’s the jeep stop?' },
          { t: 'Bayad po. Isa, Cubao.', en: 'Here’s my fare: one, to Cubao.' },
          { t: 'Pakisabi po ’pag nasa simbahan na tayo.', en: 'Please tell me when we get to the church.' },
          { t: 'Para po! Sa tabi lang po.', en: 'Stop, please! By the side is fine.' },
        ],
        scenes: [
          { kind: 'What do you ask?', prompt: 'You’ve just gotten on a jeep, and you’re not sure it goes through Cubao.', right: 'Dadaan po ba ’to sa Cubao?', wrong: ['Nasaan po ang Cubao?', 'Saan po kayo bababa?'],
            note: '“Nasaan po ang Cubao?” asks where Cubao is, not whether the jeep goes there.' },
          { kind: 'What do you say?', prompt: 'A woman on the jeep asks you, “Saan ka bababa?” You’re getting off beside the church.', right: 'Sa tabi po ng simbahan.', wrong: ['Galing po ako sa simbahan.', 'Nasa loob po ako ng simbahan.'],
            note: '“Galing po ako sa simbahan” means you’ve just come from the church.' },
          { kind: 'What do you say?', prompt: 'Your stop is coming up, and you want the driver to pull over.', right: 'Para po! Sa tabi lang po.', wrong: ['Bayad po. Isa, Cubao.', 'Diretso lang po.'],
            note: '“Diretso lang po” tells him to keep going straight.' },
        ],
      },
      {
        id: 'handaan', title: 'Handaan', sub: 'Birthday party',
        blurb: 'A family birthday party, where there’s always more food: the little words.',
        done: 'Panalo!', doneNote: '“Panalo!” means “That’s a winner!”',
        dialog: {
          setting: 'Paolo arrives late at his aunt Lorna’s birthday party, at her house.',
          people: { A: 'Paolo', B: 'Lorna' },
          lines: [
            { who: 'A', t: 'Happy birthday po, Tita Lorna! Ito po, ensaymada para sa inyo.', en: 'Happy birthday, Tita Lorna! Here, some ensaymada for you.' },
            { who: 'B', t: 'Paolo! Naku, nag-abala ka pa. Akala ko hindi ka na darating!', en: 'Paolo! Oh, you shouldn’t have. I thought you weren’t coming after all!',
              note: '“Nag-abala ka pa” is “you went to the trouble”: what you say for a gift.' },
            { who: 'A', t: 'Pasensiya na po, na-traffic kasi ako sa Ortigas. Ang dami pala ng bisita ninyo!', en: 'Sorry, I got stuck in traffic in Ortigas. Wow, you’ve got so many guests!',
              note: '“Na-traffic” is Taglish: “stuck in traffic.”' },
            { who: 'B', t: 'Oo, halos kumpleto kami. Nasaan nga pala ang mama mo?', en: 'Yes, we’re almost all here. By the way, where’s your mom?',
              note: '“Nga pala” means “by the way.”' },
            { who: 'A', t: 'Nasa Cebu po si Mama. Miss na raw po niya kayo.', en: 'Mom’s in Cebu. She says she misses you.' },
            { who: 'B', t: 'Ay, miss ko na rin siya! Sige, kumain ka na.', en: 'Oh, I miss her too! Go ahead and eat.' },
            { who: 'A', t: 'Ang sarap naman ng pansit! Kayo po ba ang nagluto?', en: 'This pancit is so good! Did you make it?' },
            { who: 'B', t: 'Oo naman! Pampahaba ng buhay ’yan. Kain ka pa!', en: 'Of course! It’s for a long life. Have some more!',
              note: 'Pancit is a birthday must: long noodles for a long life.' },
            { who: 'A', t: 'Busog na busog na po ako, Tita. Nakatatlong plato na nga po ako!', en: 'I’m stuffed, Tita. I’ve had three plates already!',
              note: '“Busog na busog” is “really full”: a word said twice, joined by na, is stronger.' },
            { who: 'B', t: 'Sayang, ang dami pang leche flan. Mag-uwi ka na lang.', en: 'Too bad, there’s still so much leche flan. Just take some home, then.',
              note: '“Sayang” is “what a waste” or “too bad.”' },
            { who: 'A', t: 'Naku, nakakahiya naman po. Konti lang po, ha?', en: 'Oh, you’re too kind. Just a little, okay?',
              note: '“Nakakahiya” is “it’s embarrassing”: the polite thing to say when someone is generous.' },
            { who: 'B', t: 'Ano ka ba, pamilya naman tayo! Iuwi mo na lahat ’yan.', en: 'Oh, come on, we’re family! Take it all home.',
              note: '“Ano ka ba” is “come on”; word for word, “what are you?”' },
          ],
        },
        questions: [
          { q: 'What does Paolo bring his tita?', right: 'Ensaymada', wrong: ['Leche flan', 'Pancit'], line: 1 },
          { q: 'Why is Paolo late?', right: 'He got stuck in traffic', wrong: ['He was in Cebu', 'He stopped to buy ensaymada'], line: 3 },
          { q: 'Where is Paolo’s mom?', right: 'In Cebu', wrong: ['At the party', 'Stuck in traffic'], line: 5 },
          { q: 'Who made the pancit?', right: 'Tita Lorna', wrong: ['Paolo’s mom', 'They bought it'], line: 8 },
          { q: 'How many plates has Paolo had?', right: 'Three', wrong: ['Two', 'Just one'], line: 9 },
          { q: 'What does Tita Lorna tell him to take home?', right: 'All the leche flan', wrong: ['Just a little leche flan', 'The rest of the pancit'], line: 12 },
        ],
        gaps: [
          { line: 2, word: 'pa', wrong: ['na', 'lang'] },
          { line: 6, word: 'rin', wrong: ['raw', 'pa'] },
          { line: 10, word: 'na', wrong: ['pa', 'rin'] },
        ],
        grammar: {
          title: 'The little words',
          points: [
            'The little words sit right after the first word or phrase. A short pronoun (ka, ko, mo) goes before them, a longer one (ako, siya, kayo) after, and po goes in among them: Kumain ka na ba? (have you eaten?) → Kumain na ba siya? (has she?) → Kumain na po ba kayo? (to an elder).',
            'Na is “now” or “already”; pa is “still”, “yet” or “more”: busog → busog na (full now), kain → kain pa! (have more!). With hindi: hindi na (not anymore), hindi pa (not yet). Na lang is “instead” or “just…, then”: mag-uwi ka na lang (just take some home, then).',
            'Rin is “too” (din after a consonant, except w and y; many people say din either way): ako → ako rin (me too). Lang is “just” or “only”: isa → isa lang (just one). Naman adds warmth (oo naman, of course!) or turns to someone else (ikaw naman, your turn).',
            'Kasi gives the reason: na-traffic kasi ako (I got stuck in traffic, you see). Pala is “oh, so…!”, for what you just found out; nga pala is “by the way”. Raw (daw after a consonant, like din) passes on what someone said: miss na raw niya kayo (she says she misses you).',
          ],
          table: [['busog', 'busog na', 'full now'], ['hindi', 'hindi pa', 'not yet'], ['masarap', 'masarap din', 'good too'], ['konti', 'konti lang', 'just a little'], ['sayang', 'sayang naman', 'what a shame']],
        },
        forms: [
          { prompt: 'Maaga ___! Kumain ka muna.', right: 'pa', wrong: ['na', 'lang'], en: 'It’s still early! Have something to eat first.' },
          { prompt: 'Ubos ___ ang lechon!', right: 'na', wrong: ['pa', 'lang'], en: 'The lechon’s all gone already!' },
          { prompt: 'Masarap ___ ang kare-kare mo, Ate.', right: 'din', wrong: ['na', 'lang'], en: 'Your kare-kare is good too, Ate.' },
          { prompt: 'Si Lola ___ ang hindi pa kumakain.', right: 'lang', wrong: ['na', 'pa'], en: 'Lola’s the only one who hasn’t eaten yet.' },
          { prompt: 'Hindi ako nakapunta, nasa Baguio ___ ako.', right: 'kasi', wrong: ['pala', 'raw'], en: 'I couldn’t make it, because I was in Baguio.' },
          { prompt: 'Tapos na ako. Ikaw ___ ang kumanta!', right: 'naman', wrong: ['lang', 'pa'], en: 'I’m done. Now it’s your turn to sing!' },
        ],
        builds: [
          { t: 'Gusto mo pa ba ng pansit?', en: 'Do you want more pancit?' },
          { t: 'Na-traffic kasi ako sa Ortigas.', en: 'I got stuck in traffic in Ortigas, you see.' },
          { t: 'Mag-uwi ka na lang ng leche flan.', en: 'Just take some leche flan home.' },
          { t: 'Mukha pa rin po kayong bata!', en: 'You still look young!' },
        ],
        says: [
          { t: 'Pasensiya na po, na-late ako.', en: 'Sorry I’m late.' },
          { t: 'Ang sarap naman ng pansit!', en: 'This pancit is so good!' },
          { t: 'Busog na busog na po ako.', en: 'I’m completely full.' },
          { t: 'Nakakahiya naman po.', en: 'Oh, you’re too kind.',
            note: 'Word for word “how embarrassing”: said when someone is generous, before you accept.' },
          { t: 'Nag-abala pa po kayo!', en: 'You shouldn’t have!',
            note: 'To a friend: “Nag-abala ka pa!”' },
        ],
        scenes: [
          { kind: 'What do you say?', prompt: 'Your tita keeps piling food on your plate, and you can’t eat another bite.', right: 'Busog na busog na po ako.', wrong: ['Konti pa po.', 'Hindi pa po ako busog.'],
            note: '“Konti pa po” is “a little more, please.”' },
          { kind: 'What do you say?', prompt: 'Your tita packs you a big container of leche flan to take home.', right: 'Nakakahiya naman po.', wrong: ['Sayang naman po.', 'Mag-uwi ka na lang.'],
            note: '“Mag-uwi ka na lang” is what she says: “just take some home.”' },
          { kind: 'What do you ask?', prompt: 'Chatting with your cousin, you realize you haven’t seen Lola all night.', right: 'Nasaan nga pala si Lola?', wrong: ['Kumain na ba si Lola?', 'Sino ang nagluto ng pansit?'],
            note: '“Kumain na ba si Lola?” asks if she has eaten.' },
        ],
      },
      {
        id: 'sa-telepono', title: 'Sa telepono', sub: 'On the phone',
        blurb: 'A phone call to plan the weekend: the future, and wanting, needing and being able to.',
        done: 'Ayos na ayos!', doneNote: '“Ayos na ayos!” means “Perfect!”',
        dialog: {
          setting: 'Nico phones his older cousin Carmi one evening to plan Saturday.',
          people: { A: 'Nico', B: 'Carmi' },
          lines: [
            { who: 'A', t: 'Hello, Ate Carmi? Si Nico ’to. May gagawin ka ba sa Sabado?', en: 'Hello, Ate Carmi? It’s Nico. Are you doing anything on Saturday?' },
            { who: 'B', t: 'Uy, Nico! Wala pa naman. Bakit?', en: 'Hey, Nico! Nothing yet. Why?' },
            { who: 'A', t: 'Pupunta kami sa Tagaytay. Kakain kami ng bulalo. Gusto mo bang sumama?', en: 'We’re going up to Tagaytay for bulalo. Want to come along?',
              note: '“Bulalo” is beef shank and bone-marrow soup, the dish Tagaytay is known for.' },
            { who: 'B', t: 'Game ako! Sino-sino ang sasama?', en: 'I’m in! Who’s coming?' },
            { who: 'A', t: 'Sina Mark at Bea. Dapat tayong umalis nang maaga para ’di tayo ma-traffic.', en: 'Mark and Bea. We should leave early so we don’t get stuck in traffic.',
              note: '“Ma-traffic” is Taglish: ma- with the English “traffic”, to get stuck in it.' },
            { who: 'B', t: 'Naku, may pasok ako hanggang alas-diyes. Puwede ba akong sumunod na lang?', en: 'Oh no, I have work until ten. Can I just follow you there later?',
              note: '“May pasok” means you have work or school that day.' },
            { who: 'A', t: '’Wag na. Hihintayin ka na lang namin. Susunduin ka namin sa opisina.', en: 'No need. We’ll just wait for you. We’ll pick you up at your office.' },
            { who: 'B', t: 'Talaga? Salamat! Magluluto ako ng turon para sa biyahe.', en: 'Really? Thanks! I’ll make turon for the drive.' },
            { who: 'A', t: 'Ayos! Kailangan mo ring magdala ng jacket. Malamig doon.', en: 'Nice! You’ll need to bring a jacket too. It’s cold up there.' },
            { who: 'B', t: 'Sige. Anong oras tayo uuwi?', en: 'Okay. What time are we heading home?' },
            { who: 'A', t: 'Bago dumilim. Ayokong magmaneho sa gabi.', en: 'Before dark. I don’t want to drive at night.',
              note: '“Ayoko” is “ayaw ko” run together: “I don’t want to.”' },
            { who: 'B', t: 'Okay! Text mo ako kapag malapit na kayo. Kitakits sa Sabado!', en: 'Okay! Text me when you’re close. See you Saturday!',
              note: '“Kitakits” is playful slang for “magkita tayo”, “let’s meet up.”' },
          ],
        },
        questions: [
          { q: 'What are they going to Tagaytay for?', right: 'Bulalo', wrong: ['Turon', 'Pancit'], line: 3 },
          { q: 'Why does Nico want to leave early?', right: 'To beat the traffic', wrong: ['To be home before dark', 'To get a good table'], line: 5 },
          { q: 'Why can’t Carmi leave early?', right: 'She has work until ten', wrong: ['She has to cook first', 'She has to help her mom'], line: 6 },
          { q: 'What does Nico offer to do?', right: 'Wait and pick her up at work', wrong: ['Leave without her', 'Meet her in Tagaytay'], line: 7 },
          { q: 'What will Carmi make for the drive?', right: 'Turon', wrong: ['Bulalo', 'Sandwiches'], line: 8 },
          { q: 'Why will they head home before dark?', right: 'Nico doesn’t want to drive at night', wrong: ['It gets cold there at night', 'Carmi has work the next day'], line: 11 },
        ],
        gaps: [
          { line: 3, word: 'Kakain', wrong: ['Kumain', 'Kumakain'] },
          { line: 9, word: 'magdala', wrong: ['magdadala', 'nagdadala'] },
          { line: 10, word: 'uuwi', wrong: ['umuwi', 'umuuwi'] },
        ],
        grammar: {
          title: 'Will, want, need, can',
          points: [
            'The not-yet-started form repeats the start of the root, up to its first vowel: kain → kakain (will eat), uwi → uuwi (will go home). The -um- of kumain drops out, but mag- and -in stay: magluto → magluluto (will cook), sunduin → susunduin (will pick up).',
            'When a verb follows gusto, ayaw, kailangan, puwede or dapat with a linker, it takes its base form, the one in commands (Kumain ka!): Gusto kong pumunta (I want to go), Kailangan mong magdala (you need to bring). An -um- verb’s base form looks like its finished one.',
            'The linker is -ng on the word just before the verb, even a little word (Gusto mo bang sumama?). A word ending in n just adds -g (Kailangan mo ring magdala); after other consonants it’s na (Gusto ni Mark na sumama).',
            'Gusto, ayaw and kailangan take ko, mo, natin: Kailangan nating umalis. Puwede and dapat take ako, ka, tayo before an -um- or mag- verb (Puwede ba tayong magkita bukas?), but ko, mo before an -in verb (Puwede ko bang sunduin si Lola?). Ayaw ko is usually said ayoko.',
          ],
          table: [['kain', 'kakain', 'will eat'], ['punta', 'pupunta', 'will go'], ['magluto', 'magluluto', 'will cook'], ['sunduin', 'susunduin', 'will pick up'], ['gusto + punta', 'gusto kong pumunta', 'I want to go']],
        },
        forms: [
          { prompt: 'Bukas, ___ ako ng bagong sapatos.', root: 'bili', right: 'bibili', wrong: ['bumili', 'bumibili'], en: 'Tomorrow I’m going to buy new shoes.' },
          { prompt: 'Mamayang gabi, ___ si Lola ng kare-kare.', root: 'luto', right: 'magluluto', wrong: ['nagluto', 'nagluluto'], en: 'Tonight, Grandma is going to cook kare-kare.' },
          { prompt: 'Sa susunod na linggo, ___ namin si Lolo sa airport.', root: 'sundo', right: 'susunduin', wrong: ['sinundo', 'sinusundo'], en: 'Next week we’re picking up Grandpa at the airport.' },
          { prompt: 'Gusto kong ___ ng halo-halo mamaya.', root: 'kain', right: 'kumain', wrong: ['kakain', 'kumakain'], en: 'I want to have halo-halo later.' },
          { prompt: 'Kailangan mong ___ nang maaga bukas.', root: 'gising', right: 'gumising', wrong: ['gigising', 'gumigising'], en: 'You need to get up early tomorrow.' },
          { prompt: 'Puwede ba akong ___ sa inyo mamaya?', root: 'daan', right: 'dumaan', wrong: ['dadaan', 'dumadaan'], en: 'Can I drop by your place later?' },
        ],
        builds: [
          { t: 'Dapat tayong umalis nang maaga.', en: 'We should leave early.',
            note: 'With a finished verb, dapat means “should have”: Dapat nagdala ako ng jacket.' },
          { t: 'Kailangan kong umuwi bago dumilim.', en: 'I need to go home before dark.' },
          { t: 'Kakain ako ng bulalo sa Tagaytay.', en: 'I’m going to have bulalo in Tagaytay.' },
          { t: 'Ayokong magmaneho sa gabi.', en: 'I don’t want to drive at night.' },
        ],
        says: [
          { t: 'May gagawin ka ba sa Sabado?', en: 'Are you doing anything on Saturday?' },
          { t: 'Gusto mo bang sumama?', en: 'Do you want to come along?',
            note: 'Said fast, the -ng often drops: “Gusto mo ba sumama?”' },
          { t: 'Susunduin kita sa inyo.', en: 'I’ll pick you up at your place.',
            note: '“Kita” is “I … you” in one word: ko and ka together.' },
          { t: 'Anong oras tayo aalis?', en: 'What time are we leaving?' },
          { t: 'Kitakits sa Sabado!', en: 'See you Saturday!' },
        ],
        scenes: [
          { kind: 'What do you ask?', prompt: 'You want to know if a friend is free this Saturday.', right: 'May gagawin ka ba sa Sabado?', wrong: ['Ano ang ginawa mo noong Sabado?', 'Saan ka pumunta noong Sabado?'],
            note: '“Ano ang ginawa mo noong Sabado?” is “What did you do last Saturday?”' },
          { kind: 'What do you ask?', prompt: 'Your friends are leaving early, but you work until noon. Ask if you can just come later.', right: 'Puwede ba akong sumunod na lang?', wrong: ['Puwede ba akong sumama?', 'Sino-sino ang sasama?'],
            note: '“Puwede ba akong sumama?” asks to come along, not to come later.' },
          { kind: 'What do you say?', prompt: 'You’re driving on Saturday. Tell your friend you’ll come get her at her house.', right: 'Susunduin kita sa inyo.', wrong: ['Sinundo kita sa inyo.', 'Sunduin mo ako sa amin.'],
            note: '“Sinundo kita” is “I picked you up”: it already happened.' },
        ],
      },
      {
        id: 'kuwentuhan', title: 'Kuwentuhan', sub: 'Telling a story',
        blurb: 'Telling a friend at work why you were late: tying a story together.',
        done: 'Ang husay mong magkuwento!', doneNote: '“Ang husay mong magkuwento!” means “You tell a story so well!”',
        dialog: {
          setting: 'At the office, Joy asks her coworker Carlo why he came in late.',
          people: { A: 'Carlo', B: 'Joy' },
          lines: [
            { who: 'B', t: 'Carlo, bakit ka na-late kanina? May nangyari ba?', en: 'Carlo, why were you late this morning? Did something happen?',
              note: '“Na-late” is Taglish: the English “late” with na-, for something that happened to you.' },
            { who: 'A', t: 'Naku, Joy, mahabang kuwento! Naiwan ko kasi ang susi sa loob ng bahay.', en: 'Oh man, Joy, it’s a long story! See, I left my key inside the house.' },
            { who: 'B', t: 'Hala! Paano nangyari ’yon?', en: 'Oh no! How did that happen?' },
            { who: 'A', t: 'Bago ako umalis, nagtapon muna ako ng basura. Tapos, biglang sumara ang pinto!', en: 'Before I left, I took out the trash first. Then the door suddenly swung shut!' },
            { who: 'B', t: '’Di ba nasa bahay ang misis mo?', en: 'Wasn’t your wife home?',
              note: '“Misis”, from the English “Mrs.”, is an everyday word for “wife.”' },
            { who: 'A', t: 'Oo, pero naliligo siya, kaya hindi niya ako narinig. Kumatok ako nang kumatok!', en: 'She was, but she was in the shower, so she didn’t hear me. I knocked and knocked!',
              note: '“Kumatok nang kumatok”: a verb said twice, joined by nang, is doing it over and over.' },
            { who: 'B', t: 'Kawawa ka naman! Tapos?', en: 'Oh, you poor thing! And then?' },
            { who: 'A', t: 'Habang naghihintay ako, binigyan ako ni Aling Nena ng mainit na kape.', en: 'While I waited, Aling Nena gave me a cup of hot coffee.' },
            { who: 'B', t: 'Ang bait naman ng kapitbahay mo! Matagal ka bang naghintay?', en: 'Your neighbor’s so kind! Did you wait long?' },
            { who: 'A', t: 'Mga kalahating oras. Noong binuksan ni misis ang pinto, tawa siya nang tawa!', en: 'About half an hour. When my wife opened the door, she laughed and laughed!' },
            { who: 'B', t: 'Kaya ka pala na-late! Sa susunod, dalhin mo ang susi bago ka lumabas, ha?', en: 'So that’s why you were late! Next time, take your key before you go out, OK?',
              note: '“Kaya pala” is “so that’s why,” when something finally makes sense.' },
            { who: 'A', t: 'Oo na, oo na! ’Yan din ang sabi ni misis pagkatapos niyang tumawa.', en: 'OK, OK! My wife said the same thing, once she stopped laughing.' },
          ],
        },
        questions: [
          { q: 'What did Carlo leave inside the house?', right: 'His key', wrong: ['His phone', 'His wallet'], line: 2 },
          { q: 'What was he doing when the door shut?', right: 'Taking out the trash', wrong: ['Drinking coffee', 'Taking a shower'], line: 4 },
          { q: 'Why didn’t his wife hear him knocking?', right: 'She was in the shower', wrong: ['She was still asleep', 'She was at the neighbor’s'], line: 6 },
          { q: 'Who gave him coffee while he waited?', right: 'Aling Nena', wrong: ['His wife', 'Joy'], line: 8 },
          { q: 'How long did he wait outside?', right: 'About half an hour', wrong: ['About ten minutes', 'About an hour'], line: 10 },
          { q: 'What does Joy tell him to do next time?', right: 'Take his key before he goes out', wrong: ['Knock louder', 'Leave earlier for work'], line: 11 },
        ],
        gaps: [
          { line: 4, word: 'Bago', wrong: ['Habang', 'Pagkatapos'] },
          { line: 6, word: 'kaya', wrong: ['kasi', 'habang'] },
          { line: 8, word: 'na', wrong: ['ng', 'nang'] },
        ],
        grammar: {
          title: 'Tying a story together',
          points: [
            'Kasi (because) gives the reason and kaya (so) the result: naliligo siya, kaya hindi niya ako narinig → hindi niya ako narinig kasi naliligo siya. Tapos (then) moves the story on; pero (but) turns it.',
            'Bago (before) and pagkatapos (after) take the base form, the one in commands, even about the past: alis → bago ako umalis (before I left); ligo → pagkatapos kong maligo (after I showered). Pagkatapos takes kong, mong, niyang, not ako, ka, siya; before a noun, ng: pagkatapos ng trabaho (after work).',
            'Habang (while) takes the still-going form: hintay → habang naghihintay ako (while I waited). Noong (when, in the past) takes the finished form for something that happened once: gising → noong nagising ako (when I woke up).',
            'A linker joins a describing word and its noun, either way round: -ng after a vowel, -g after n, na after anything else. maganda → magandang bahay, bahay na maganda; mainit → mainit na kape; isang daan → isang daang tao. It joins a noun and a verb, too: ang batang umiiyak (the child who’s crying).',
          ],
          table: [['luto', 'bago magluto', 'before cooking'], ['luto', 'habang nagluluto', 'while cooking'], ['luto', 'noong nagluto', 'when (I) cooked'], ['luto', 'pagkatapos magluto', 'after cooking'], ['maganda', 'magandang bahay, bahay na maganda', 'a beautiful house']],
        },
        forms: [
          { prompt: 'Magsipilyo ka bago ___.', root: 'tulog', right: 'matulog', wrong: ['natulog', 'natutulog'], en: 'Brush your teeth before bed.' },
          { prompt: 'Habang ___ ako ng pinggan, may kumatok sa pinto.', root: 'hugas', right: 'naghuhugas', wrong: ['naghugas', 'maghuhugas'], en: 'While I was washing the dishes, someone knocked at the door.' },
          { prompt: 'Noong ___ ako kagabi, tulog na ang mga bata.', root: 'dating', right: 'dumating', wrong: ['dumarating', 'darating'], en: 'When I got home last night, the kids were already asleep.' },
          { prompt: 'Pagkatapos kong ___, nagbihis ako agad.', root: 'ligo', right: 'maligo', wrong: ['naligo', 'naliligo'], en: 'After I showered, I got dressed right away.' },
          { prompt: 'May ___ aso ang kapitbahay namin.', root: 'malaki', right: 'malaking', wrong: ['malaki', 'malaki na'], en: 'Our neighbor has a big dog.' },
          { prompt: 'Sino ang ___ kumakanta sa kabilang bahay?', root: 'babae', right: 'babaeng', wrong: ['babae', 'babae na'], en: 'Who’s the woman singing next door?' },
        ],
        builds: [
          { t: 'Na-late ako kasi ang bigat ng traffic.', en: 'I was late because the traffic was so bad.' },
          { t: 'Umulan nang malakas, kaya hindi kami umalis.', en: 'It rained hard, so we didn’t go out.' },
          { t: 'Nakatulog si Lolo habang nanonood ng balita.', en: 'Grandpa fell asleep while watching the news.' },
          { t: 'Tinulungan ako ng isang mabait na kapitbahay.', en: 'A kind neighbor helped me.' },
        ],
        says: [
          { t: 'Mahabang kuwento!', en: 'It’s a long story!' },
          { t: 'Paano nangyari ’yon?', en: 'How did that happen?' },
          { t: 'Naiwan ko ang susi sa loob.', en: 'I left my key inside.' },
          { t: 'Kaya ka pala na-late!', en: 'So that’s why you were late!' },
          { t: 'Dalhin mo ang susi bago ka lumabas.', en: 'Take your key before you go out.' },
        ],
        scenes: [
          { kind: 'What do you ask?', prompt: 'A friend says he got locked out of his house this morning. You want to know how.', right: 'Paano nangyari ’yon?', wrong: ['Kailan nangyari ’yon?', 'Sino ang kasama mo?'],
            note: '“Kailan nangyari ’yon?” asks when it happened, not how.' },
          { kind: 'What do you say?', prompt: 'A friend at work asks why you were late. It’s a long, funny story.', right: 'Mahabang kuwento!', wrong: ['Kaya ka pala na-late!', 'Paano nangyari ’yon?'],
            note: '“Kaya ka pala na-late!” is for the one listening: “So that’s why you were late!”' },
          { kind: 'What do you say?', prompt: 'Your son is going out with his friends. Remind him to take the house key.', right: 'Dalhin mo ang susi bago ka lumabas.', wrong: ['Naiwan ko ang susi sa loob.', 'Kumain ka muna bago ka umalis.'],
            note: '“Naiwan ko ang susi sa loob” is “I left my key inside.”' },
        ],
      },
    ],
  };

  if (typeof module !== 'undefined' && module.exports) module.exports = COURSE;
  else (root.AMIGO_COURSES = root.AMIGO_COURSES || {}).tl2 = COURSE;
})(this);
