#!/usr/bin/env node
// Builds content/reading.js: the text of every chapter in each week's
// reading block (the `reference` in content/weeks.js, like "Isaiah 40–49"
// or "Isaiah 13–14; 22; 24–30; 35"), so he can read the chapters themselves
// in the app. Same pinned public-domain data as tools/verify.mjs.
//
// The deploy runs this after the content check, so a week added from
// developer mode gets its chapters with no extra step. The file isn't kept
// in git. To try the reader locally: node tools/verify.mjs once (it
// downloads the data), then  node tools/build-reading.mjs
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');
const CACHE = process.env.SCRIPTURE_CACHE || path.join(ROOT, 'tools', '.scripture-cache');
const VOLUMES = ['old-testament', 'new-testament', 'book-of-mormon', 'doctrine-and-covenants', 'pearl-of-great-price'];

const files = fs.existsSync(CACHE) ? fs.readdirSync(CACHE) : [];
const chapters = new Map();   // "Isaiah 40" -> ["Comfort ye, …", …] (verse 1 first)
for (const name of VOLUMES) {
  const f = files.find(x => x.endsWith('-' + name + '.json'));
  if (!f) throw new Error('Run node tools/verify.mjs once first, to download the scripture data');
  const data = JSON.parse(fs.readFileSync(path.join(CACHE, f), 'utf8'));
  for (const c of data.sections || data.books.flatMap(b => b.chapters)) {
    for (const v of c.verses) {
      const key = v.reference.replace(/:\d+$/, '');
      if (!chapters.has(key)) chapters.set(key, []);
      chapters.get(key)[v.verse - 1] = v.text;
    }
  }
}

// Names the lesson pages use that the data spells another way.
const ALIAS = { 'Song of Solomon': "Solomon's Song", 'Solomon’s Song': "Solomon's Song", 'Psalm': 'Psalms', 'D&C': 'Doctrine and Covenants' };
const lookup = ch => { const m = /^(.+) (\d+)$/.exec(ch); return chapters.get((ALIAS[m[1]] || m[1]) + ' ' + m[2]); };

// "Ezra 1; 3–7; Nehemiah 2; 4–6" -> ["Ezra 1", "Ezra 3", …, "Nehemiah 6"].
// A part with verses ("Genesis 5:21–24") still brings its whole chapter, and
// a book on its own ("Hosea 1–6; Joel") brings every chapter of it.
// The app reads the block the same way (readingUnits in index.html).
function blockChapters(reference) {
  const out = [];
  let book = null;
  for (const raw of String(reference || '').split(';')) {
    const part = raw.trim();
    if (/^\d? ?[A-Za-z][^\d]*$/.test(part)) {            // a whole book
      book = part;
      for (let c = 1; lookup(book + ' ' + c); c++) out.push(book + ' ' + c);
      continue;
    }
    const m = /^(?:(.*?[A-Za-z].*?) )?(\d+)(?::\d+(?:[–-]\d+)?)?(?:[–-](\d+))?$/.exec(part);
    if (!m) throw new Error(`Can't read the reading block "${reference}" (at "${part}")`);
    if (m[1]) book = m[1];
    if (!book) throw new Error(`The reading block "${reference}" must start with a book`);
    const to = /:/.test(part) ? Number(m[2]) : Number(m[3] || m[2]);
    for (let c = Number(m[2]); c <= to; c++) out.push(book + ' ' + c);
  }
  return out;
}

const src = fs.readFileSync(path.join(ROOT, 'content', 'weeks.js'), 'utf8');
const MARK = 'window.TU_WEEKS = ';
const weeks = JSON.parse(src.slice(src.indexOf(MARK) + MARK.length, src.lastIndexOf(';')));

// A chapter it can't find is a warning, not a failure: the app then sends
// him to Gospel Library for it, so it never blocks a deploy.
const out = {};
let missing = 0;
for (const w of weeks) {
  let list = [];
  try { list = blockChapters(w.reference); } catch (e) { console.warn('⚠', w.dates + ':', e.message); missing++; }
  for (const ch of list) {
    const verses = lookup(ch);
    if (verses) out[ch] = verses;
    else { console.warn(`⚠ ${w.dates}: "${ch}" (from "${w.reference}") isn't in the scripture data`); missing++; }
  }
}
fs.writeFileSync(path.join(ROOT, 'content', 'reading.js'),
  '// Generated by tools/build-reading.mjs at deploy: the chapters of each week\'s reading.\n' +
  '// Do not edit by hand.\n' +
  'window.TU_READING = ' + JSON.stringify(out) + ';\n');
console.log(`content/reading.js: ${Object.keys(out).length} chapters` + (missing ? `, ${missing} not found (read in Gospel Library)` : ''));
